//! Text for humans and hosts: the heartbeat protocol and the STATE.md projection.

use crate::session::{self, Host};
use crate::state::State;
use crate::tick;
use crate::todo;
use anyhow::{bail, Result};
use std::path::Path;

pub const HOSTS: [&str; 3] = ["claude", "codex-app", "codex-cli"];

const PROTOCOL: &str = "你在为目标「{goal}」持续工作。项目目录：{root}（所有命令在这里执行）。每一轮：
1. 先运行 `zloop context` 读交接包，再运行 `zloop next --json`。should_run=false 时，按 reason 简短告知用户后停止本轮，不要做别的。
2. should_run=true 时，只做 todo 里这一条：做出可验证的产物，能跑的就跑一下验证。
3. 完成 → `zloop done <id> --note \"<一句话结果>\" [--evidence \"<细节或 @文件>\"]`；有进展没做完 → 加 `--outcome progress`；失败 → 加 `--outcome fail`；需要用户决定 → 加 `--block \"<问题>\"`；发现新任务 → 加 `--next \"<任务>\"`。
4. 不要改 .zloop/ 以外的调度状态；不碰凭证、不做破坏性 git、不做生产操作。
5. 每轮结束用两三句话告诉用户：做了什么、验证了什么、下一条是什么。";

fn host_tail(host: &str) -> &'static str {
    match host {
        "claude" => "续跑方式：在 Claude Code 里输入 `/loop /zloop`；每轮 interval_min 是建议的下次间隔（分钟），为 null 表示停下等人。",
        "codex-app" => "续跑方式：用 automation_update 建一条 automation，body 就是本段文字，初始间隔 3 分钟；按每轮 interval_min 调整间隔，为 null 时暂停 automation。",
        _ => "续跑方式：`/goal <本段文字>`。连续 3 轮 should_run=false 则 `update_goal status=blocked`，等用户 `/goal resume`。",
    }
}

pub fn heartbeat(state: &State, host: &str, root: &Path) -> Result<String> {
    if !HOSTS.contains(&host) {
        bail!("unknown host {host:?}; expected one of {}", HOSTS.join(", "));
    }
    let body = PROTOCOL
        .replace("{goal}", &state.goal.text)
        .replace("{root}", &root.to_string_lossy());
    Ok(format!("{body}\n{}", host_tail(host)))
}

pub fn checkbox(status: &str) -> &'static str {
    match status {
        "open" => "[ ]",
        "blocked" => "[!]",
        "deferred" => "[-]",
        "done" => "[x]",
        _ => "[?]",
    }
}

pub fn render_md(state: &State, root: &Path, max_ticks: usize) -> String {
    let goal = &state.goal;
    let p = &state.policy;
    let mut out = String::new();
    out.push_str(&format!("# zloop · {}\n\n", goal.id));
    out.push_str(&format!("**Goal** ({}): {}\n\n", goal.status, goal.text));
    out.push_str(&format!(
        "policy: window {}h · max_runs {} · fail_streak {} · noop_streak {} · intervals {:?} min\n\n",
        p.window_hours, p.max_runs, p.max_fail_streak, p.max_noop_streak, p.intervals_min
    ));
    out.push_str("## Todos\n\n");
    let mut order: Vec<&_> = state.todos.iter().collect();
    order.sort_by_key(|t| (todo::is_terminal(&t.status), t.priority));
    for t in &order {
        let deps = if t.blocked_by.is_empty() { String::new() } else { format!(" ⏳{}", t.blocked_by.join(",")) };
        let note = if t.note.is_empty() { String::new() } else { format!(" — {}", t.note) };
        out.push_str(&format!("- {} `{}` [P{}] {}{}{}\n", checkbox(&t.status), t.id, t.priority, t.text, deps, note));
    }
    if state.todos.is_empty() {
        out.push_str("- (none yet — run `zloop plan`)\n");
    }
    out.push_str(&format!("\n## Recent ticks (round {})\n\n", tick::current_round(&state.ticks)));
    let start = state.ticks.len().saturating_sub(max_ticks);
    for t in &state.ticks[start..] {
        let who = match &t.todo { Some(id) => format!(" {id}"), None => String::new() };
        let note = if t.note.is_empty() { String::new() } else { format!(": {}", t.note) };
        let mut tail = String::new();
        if let (Some(h), Some(s)) = (&t.host, &t.session) {
            if let Some(cmd) = Host::parse(h).and_then(|hh| session::resume_command(hh, s)) {
                tail.push_str(&format!(" · `{cmd}`"));
            }
        }
        if let Some(log) = &t.log {
            tail.push_str(&format!(" · [log]({log})"));
        }
        out.push_str(&format!("- {}{} **{}**{}{}\n", t.at, who, t.outcome, note, tail));
    }
    if state.ticks.is_empty() {
        out.push_str("- (no ticks yet)\n");
    }
    let sessions = session::summarize(state, root);
    if !sessions.is_empty() {
        out.push_str("\n## Sessions\n\n");
        for s in sessions {
            out.push_str(&format!(
                "- {} `{}` · {} ticks · {}\n",
                s.host,
                s.session,
                s.ticks,
                s.resume.unwrap_or_default()
            ));
        }
    }
    out.push_str(&format!("\n_updated {} · generated by zloop, do not edit_\n", state.updated_at));
    out
}
